[milesmcc]
name = "Miles McCain"
website = "https://miles.land"
github = "milesmcc"
email = "privacyspy@sendmiles.email"
role = "founder"

[ibarakaiev]
name = "Igor Barakaiev"
website = "https://igor.fyi"
github = "ibarakaiev"
email = "privacyspy@igor.fyi"
role = "founder"

[doamatto]
name = "Matt Ronchetto"
website = "https://www.doamatto.xyz"
github = "doamatto"
email = "ps@doamatto.xyz"

[kulchynska]

[YuriiStasiuk]

[UnKnOwN]

[jacktheripper]

[Gia]

[Jelle]

[owlswipe]

[yaagesoft]

[newuser_mnWFF]

[kqgWt]

[nep]

[newuser_TY8Zz]

[tr1t0n]

[AlexThurman]

[nsoares]

[TheDeafCreeper]

[martin89up]

[jakecowton]

[newuser_uNZdE]

[newuser_3TX3H]

[unbeatable101]
github = "unbeatable-101"

[RambosRide]

[andreww88]

[newuser_nv51b]

[newuser_sCYZS]

[newuser_PMi0H]

[noodlemind]

[newuser_vDj3B]

[bumbleben]

[LeylaJ]

[junkerjenkins]

[ftsell]

[Anastasia]

[Palovt]

[MillironX]

[newuser_xK4YJ]

[VukAnd12]

[newuser_JEm5B]

[notsonewuser]

[vutut]
github = "vutut"
email = "vutut@posteo.net"

[101AustinTech]

[newuser_9V4YB]

[newuser_0lVm1]

[newuser_SpxcB]

[cvieira]
name = "Conner Vieira"
website = "https://v0lttech.com"
github = "connervieira"
email = "cvieira@v0lttech.com"
role = "contributor"

[SCT339]

[newuser_0RaMz]

[hwerfipwefpbifqwiqwffui]

[4Iufy]

[WatchfulFrog]

[JanaR]

[Faro]

[Donno]

[Anonymous]

[newuser_frLoi]

[newuser_CTscb]

[PSalant]

[justaprivacycom]

[newuser_Qr8Dd]

[mrhedgehog0]

[Wingo5315]

[Quill]
name = "Quill Moss"
email = "qmoss2021@gmail.com"

[captainmeta4]
name = "Adam LaDine"
github = "captainmeta4"

[erotavlas]
name = "erotavlas"
email = "erotavlas@pm.me"

[Deivedux]
name = "Deividas Losikov"
github = "Deivedux"

[tpdcl]

[elijahpepe]
name = "Elijah Conners"
github = "ElijahPepe"

[sjoseph7]
github = "sjoseph7"

[Okula]
github = "Dev-Okula"

[davidbernau]
github = "davidbernau"
