name = "IONOS by 1&1"
description = "IONOS by 1&1 is a web hosting company owned by United Internet."
slug = "1-1-ionos"
hostnames = [ "ionos.com" ]
sources = [ "https://www.ionos.com/terms-gtc/terms-privacy/" ]
contributors = [ "doamatto" ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "IONOS may also use the personally identifiable information collected by IONOS to contact customers regarding products and services offered by IONOS and, to the extent the user has agreed to it, by its trusted affiliates, independent contractors and business partners. We may also use this information and share it with trusted third parties for research purposes regarding the effectiveness of our website services, marketing, advertising and sales efforts, including, without limitation, for purposes of customer reviews (such as for the utilization of programs like Google Seller Ratings). IONOS will not sell or otherwise share this information with a third party for a third party\\x92s marketing purposes, unless you specifically authorize such information sharing."
]

[rubric.security]
value = "somewhat"
citations = [
  "The information provided to IONOS is saved indefinitely and may be stored on one or more databases directly or indirectly maintained by IONOS. IONOS employs industry-standard security measures to protect the confidentiality of the information. While we cannot guarantee that loss, misuse or alteration of data will not occur, we make every effort to prevent such occurrences. Any other particularly sensitive information, such as credit card numbers collected for commercial transactions, is encrypted prior to transmission by you to IONOS. Your use of the 1&1 IONOS Inc. Services may result in the transfer of information internationally, including into or outside of the United States. By visiting accessing this site or using the 1&1 IONOS Inc. Services you consent to such transfers.",
  "While IONOS uses industry-standard measures to protect your information, no security measures are foolproof, and it is impossible to guarantee complete security of data sent or maintained via the internet."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "IONOS may also disclose aggregate, anonymous data based on information collected from users to investors and potential partners. In such cases, only statistical information will be disclosed and personally identifiable data will be kept strictly confidential. In case IONOS is sold, the information collected from users may be transferred to the new owners.",
  "IONOS may from time to time engage third parties, including its own subsidiaries and affiliated companies, to preserve, analyze or otherwise store or manipulate data received by IONOS from its customers. In all such cases, third party service providers will be required to treat all such data with the same degree of care as IONOS and they will be prohibited from disclosing such data to any other person or party, except as otherwise provided for in this Privacy Policy."
]

[rubric.history]
value = "last-modified"
citations = [ "Revised: October 12, 2018" ]

[rubric.data-deletion]
value = "no"
notes = [
  "The policy doesn't require the service to allow you to delete your data"
]

[rubric.data-breaches]
value = "no"
notes = [
  "The policy doesn't require the service to notify you in the event of a data breach"
]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "IONOS may use and share your personal information in order to provide the services requested. For example, your information may be provided to the domain registrar in order to process domain registrations, or with the relevant certificate authority to order an SSL certificate on your behalf. We will also share your information to the extent necessary to comply with ICANN's rules, regulations, and policies, and if your domains are not set to private registration, the publicly available WHOIS registry will contain personal information, including but not limited to your title, first name, surname, domain name, e-mail address, country, and phone number.",
  "IONOS is required to supply some of your personal data in order to request an SSL certificate from the certificate authority. By submitting a request for an SSL certificate order or renewal through IONOS, you consent to IONOS releasing all required personal information to the certificate authority in order to fulfill the request and you acknowledge and understand that IONOS acts only as an intermediary between the customer and the certificate authority, in order to facilitate the order or renewal of the certificate. IONOS has no influence on the outcome of an SSL certificate request and cannot guarantee that any request for an SSL certificate order or renewal will be granted.",
  "IONOS may also use the personally identifiable information collected by IONOS to contact customers regarding products and services offered by IONOS and, to the extent the user has agreed to it, by its trusted affiliates, independent contractors and business partners. We may also use this information and share it with trusted third parties for research purposes regarding the effectiveness of our website services, marketing, advertising and sales efforts, including, without limitation, for purposes of customer reviews (such as for the utilization of programs like Google Seller Ratings). IONOS will not sell or otherwise share this information with a third party for a third party\\x92s marketing purposes, unless you specifically authorize such information sharing.",
  "IONOS may also disclose aggregate, anonymous data based on information collected from users to investors and potential partners. In such cases, only statistical information will be disclosed and personally identifiable data will be kept strictly confidential. In case IONOS is sold, the information collected from users may be transferred to the new owners.",
  "IONOS may from time to time engage third parties, including its own subsidiaries and affiliated companies, to preserve, analyze or otherwise store or manipulate data received by IONOS from its customers. In all such cases, third party service providers will be required to treat all such data with the same degree of care as IONOS and they will be prohibited from disclosing such data to any other person or party, except as otherwise provided for in this Privacy Policy.",
  "IONOS uses payment account information solely to check the financial qualifications of prospective Customers and to collect payment for the services provided by IONOS."
]

[rubric.data-collection-reasoning]
value = "mostly"
citations = [
  "IONOS may use and share your personal information in order to provide the services requested. For example, your information may be provided to the domain registrar in order to process domain registrations, or with the relevant certificate authority to order an SSL certificate on your behalf. We will also share your information to the extent necessary to comply with ICANN's rules, regulations, and policies, and if your domains are not set to private registration, the publicly available WHOIS registry will contain personal information, including but not limited to your title, first name, surname, domain name, e-mail address, country, and phone number.",
  "IONOS is required to supply some of your personal data in order to request an SSL certificate from the certificate authority. By submitting a request for an SSL certificate order or renewal through IONOS, you consent to IONOS releasing all required personal information to the certificate authority in order to fulfill the request and you acknowledge and understand that IONOS acts only as an intermediary between the customer and the certificate authority, in order to facilitate the order or renewal of the certificate. IONOS has no influence on the outcome of an SSL certificate request and cannot guarantee that any request for an SSL certificate order or renewal will be granted."
]
notes = [
  "While it is mostly clear why IONOS collects personal data, the policy outlines cases where the intent is not clear (including in the answer to 'behavioral-marketing' question."
]

[rubric.noncritical-purposes]
value = "opt-out-some"
citations = [
  "IONOS may also collect information about how users access the website through log files and the use of cookies, and through third party services such as Mouseflow and Google Analytics. Such information may include standard information from your web browser (such as browser type and language), your Internet Protocol (“IP”) address, and the actions you take on IONOS's Web sites (such as the web pages viewed and the links clicked). To opt out of Mouseflow please visit www.mouseflow.com/opt-out/.",
  "Google’s ability to use and share information collected by Google Analytics about your visits to this Site is restricted by the Google Privacy Policy.  You can prevent Google Analytics from recognizing you on return visits to this Site by disabling the Google Analytics cookie on your browser",
  "Our customers and users will occasionally receive newsletters or e-mails with information on products, services, or special offers. Out of respect for the privacy of our users, IONOS gives them the opportunity to opt-out from receiving these types of communications."
]
notes = [
  "To opt-out of Google Analytics, use https://tools.google.com/dlpage/gaoptout/"
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "Though we make every effort to preserve your privacy, we may need to disclose personal information when required by law, or if IONOS believes that disclosure is necessary to protect IONOS's rights and/or to comply with a judicial proceeding, court order, subpoena or other legal process. IONOS may also disclose information about you if we determine that for national security, law enforcement, or other issues of public importance, disclosure is necessary. Please see our Subpoena Policy for more information."
]

[rubric.list-collected]
value = "summarily"
citations = [
  "IONOS may request or collect personal information from online users in a variety of ways, including through online forms for requesting information or ordering products and services, and other instances where users are invited to volunteer such information. Some of the data we collect is information that identifies you personally, and may include your name, e-mail address, postal address, telephone and telefax numbers, payment account information, and other information necessary to provide the services requested. IONOS also maintains a record of contacts for customer or technical support."
]

[rubric.revision-notify]
value = "no"
citations = [
  "IONOS reserves the right to change this Privacy Policy at any time, and such changes will be posted to the IONOS website."
]
