name = "DoubleClick"
description = "DoubleClick Digital Marketing is an integrated ad technology platform owned by Google."
hostnames = ["doubleclick.net"]
slug = "doubleclick"
parent = "google"
contributors = ["ibarakaiev"]