name = "Firefox Browser"
description = "Firefox is a popular open-source browser maintained by the non-profit technology organization Mozilla."
slug = "firefox"
hostnames = [ "mozilla.org" ]
sources = [ "https://www.mozilla.org/en-US/privacy/firefox/", "https://www.mozilla.org/en-US/privacy/" ]
contributors = [ "milesmcc", "doamatto" ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "\"Webpage data for Pocket Recommendations: We recommend content to you based on your browsing history. The process of deciding which stories you should see happens locally in your copy of Firefox and neither Mozilla nor Pocket receives a copy of your browsing history. We do receive data about the recommendations you see and click. Learn more.\""
]
notes = [
  "While Firefox suggests content based on browsing history and other factors, it happens locally on the client's side and is not used to generate profit."
]

[rubric.security]
value = "somewhat"
citations = [
  "We are committed to protecting your personal information once we have it. We implement physical, business and technical security measures."
]

[rubric.third-party-collection]
value = "no"
notes = [
  "It is not ever mentioned and likely not the case, hence the selection is \"no.\""
]

[rubric.history]
value = "last-modified"
citations = [
  "Effective March 1, 2021"
]

[rubric.data-deletion]
value = "yes-automated"
notes = [
  "It is not governed under this privacy policy, however, information regarding such can be found at https://support.mozilla.org/en-US/kb/firefox-accounts-managing-account-data#w_how-do-i-delete-my-account-data"
]

[rubric.data-breaches]
value = "eventually"
citations = [
  "Despite our efforts, if we learn of a security breach, we'll notify you so that you can take appropriate protective steps."
]

[rubric.third-party-access]
value = "yes-specified-noncritical"
citations = [
  "Campaign and Referral Data: This helps Mozilla understand the effectiveness of our marketing campaigns.\n\nOn Desktop: Firefox by default sends Mozilla HTTP data that may be included with Firefox’s installer. This enables us to determine the website domain or advertising campaign (if any) that referred you to our download page. Read the documentation or opt-out before installation.\n\nOn iOS and Android: Firefox by default sends mobile campaign data to Adjust, our analytics vendor, which has its own privacy policy. Mobile campaign data includes a Google advertising ID, IP address, timestamp, country, language/locale, operating system, and app version. Read the documentation.\n\nTechnical & Interaction Data:\n\nOn iOS and Android: Firefox by default sends data about what features you use in Firefox to Leanplum, our mobile marketing vendor, which has its own privacy policy. This data allows us to test different features and experiences, as well as provide customized messages and recommendations for improving your experience with Firefox.\n\nRead the documentation for iOS or Android, or learn how to disable this feature.\n"
]

[rubric.data-collection-reasoning]
value = "yes"
notes = [
  "The document outlines why each piece of data is collected under every tab (eg. reasoning for Location data is under the « Location » tab)"
]

[rubric.noncritical-purposes]
value = "opt-out-all"
citations = [
  "Interaction data: Firefox sends data about your interactions with Firefox to us (such as number of open tabs and windows; number of webpages visited; number and type of installed Firefox Add-ons; and session length) and Firefox features offered by Mozilla or our partners (such as interaction with Firefox search features and search partner referrals).\n\nTechnical data: Firefox sends data about your Firefox version and language; device operating system and hardware configuration; memory, basic information about crashes and errors; outcome of automated processes like updates, safebrowsing, and activation to us. When Firefox sends data to us, your IP address is temporarily collected as part of our server logs.\n\nRead the telemetry documentation for Desktop, Android, or iOS or learn how to opt-out of this data collection."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "When the law requires it. We follow the law whenever we receive requests about you from a government or related to a lawsuit. We'll notify you when we're asked to hand over your personal information in this way unless we're legally prohibited from doing so. When we receive requests like this, we'll only release your personal information if we have a good faith belief that the law requires us to do so. Nothing in this policy is intended to limit any legal defenses or objections that you may have to a third party's request to disclose your information."
]

[rubric.list-collected]
value = "generally"
citations = [
  "Technical & Interaction data: Firefox sends us data such as the position, size and placement of content we suggest, as well as basic data about your interactions with Firefox’s suggested content. This includes the number of times suggested content is displayed or clicked."
]

[rubric.revision-notify]
value = "yes"
citations = [
  "We may need to change this policy and our notices. The updates will be posted online. If the changes are substantive, we will announce the update through Mozilla's usual channels for such announcements such as blog posts and forums. Your continued use of the product or service after the effective date of such changes constitutes your acceptance of such changes. To make your review more convenient, we will post an effective date at the top of the page."
]
