name = "LinkedIn"
description = "LinkedIn is a social network for professional communication owned by Microsoft."
slug = "linkedin"
hostnames = [ "linkedin.com" ]
sources = [ "https://www.linkedin.com/legal/privacy-policy" ]
contributors = [ "Anastasia" ]

[rubric.behavioral-marketing]
value = "yes"
citations = [
  "We target (and measure the performance of) ads to Members, Visitors and others both on and off our Services directly or through a variety of partners.\n"
]

[rubric.security]
value = "yes-audits"
citations = [
  "We implement security safeguards designed to protect your data, such as HTTPS. We regularly monitor our systems for possible vulnerabilities and attacks. However, we cannot warrant the security of any information that you send us. There is no guarantee that data may not be accessed, disclosed, altered, or destroyed by breach of any of our physical, technical, or managerial safeguards. Please visit our Safety Center for additional information about safely using our Services, including two-factor authentication."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "We receive personal data about you when you use the services of our customers and partners, such as employers, prospective employers and applicant tracking systems providing us job application data.\nWe receive data about you when you use some of the other services provided by us or our affiliates, including Microsoft. For example, you may choose to send information about your contacts in Microsoft apps and services, such as Outlook, to us for improved professional networking activities on our Services."
]

[rubric.history]
value = "yes"
citations = [
  "This summary is intended to help you better understand the most recent changes to the Privacy Policy and Cookie Policy and how they may impact you."
]

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "Delete Data: You can ask us to erase or delete all or some of your personal data (e.g., if it is no longer necessary to provide Services to you).\nIf you choose to close your Linkedin (or SlideShare) account, your personal data will generally stop being visible to others on our Services within 24 hours. We generally delete closed account information within 30 days of account closure, except as noted below."
]

[rubric.data-breaches]
value = "yes-72"
citations = [
  "Notify Customer of any Personal Data Breach by LinkedIn, its Subprocessors, or any other third-parties acting on LinkedIn’s behalf without undue delay and in any event within 48 hours of becoming aware of a Personal Data Breach."
]

[rubric.third-party-access]
value = "no"
citations = [
  "We do not share your personal data with any third-party advertisers or ad networks for their advertising except for: (i) hashed or device identifiers (to the extent they are personal data in some countries); (ii) with your separate permission (e.g., lead generation form) or (iii) data already visible to any users of the Services (e.g. profile). "
]

[rubric.data-collection-reasoning]
value = "mostly"
citations = [
  "We log usage data when you visit or otherwise use our Services, including our sites, app and platform technology (e.g., our off-site plugins), such as when you view or click on content (e.g., learning video) or ads (on or off our sites and apps), perform a search, install or update one of our mobile apps, share articles or apply for jobs. We use log-ins, cookies, device information and internet protocol (“IP”) addresses to identify you and log your use."
]

[rubric.noncritical-purposes]
value = "opt-out-some"
citations = [
  " You can also opt-out specifically from our uses of certain categories of data to show you more relevant ads.\n You can also opt-out from our use of cookies and similar technologies that track your behavior on the sites of others for third party advertising"
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "It is possible that we will need to disclose information about you when required by law, subpoena, or other legal process or if we have a good faith belief that disclosure is reasonably necessary to (1) investigate, prevent, or take action regarding suspected or actual illegal activities or to assist government enforcement agencies; (2) enforce our agreements with you, (3) investigate and defend ourselves against any third-party claims or allegations, (4) protect the security or integrity of our Service (such as by sharing with companies facing similar threats); or (5) exercise or protect the rights and safety of LinkedIn, our Members, personnel, or others. "
]

[rubric.list-collected]
value = "generally"
notes = [
  "Examples of personal data are enumerated throughout the privacy policy in the Data We Collect Section. "
]

[rubric.revision-notify]
value = "yes"
citations = [
  "LinkedIn (“we” or “us”) can modify this Privacy Policy, and if we make material changes to it, we will provide notice through our Services, or by other means, to provide you the opportunity to review the changes before they become effective. If you object to any changes, you may close your account.\n\n"
]
