name = "Paddle"
description = "Paddle is a payment processing company incorporated in England and Wales."
slug = "paddle"
hostnames = [ "paddle.com" ]
sources = [ "https://paddle.com/privacy/" ]
contributors = [ "doamatto" ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "We do not share your personal information with third parties without your consent other than: With third parties who work on our behalf provided such third parties adhere to the data protection principles set out in the European Union Directive and/or Regulation on Data Protection or other applicable legilsation, or enter into a written agreement with Paddle requiring that the third party provide at least the same level of privacy protection as is required by such Principles; To comply with laws or to respond to lawful requests and legal process (provided that Paddle will endeavour to notify you if Paddle has received a lawful request for your information); To protect the rights and property of Paddle, our agents, customers and others including to enforce our agreements, policies and terms of use; In an emergency, including to protect the personal safety of any person; and For the purposes of a business deal (or negotiation of a business deal) involving sale or transfer of all or a part of our business or assets (business deals may include, for example, any merger, financing, acquisition, divestiture or bankruptcy transaction or proceeding)."
]

[rubric.security]
value = "somewhat"
citations = [
  "Paddle takes the protection of customer data extremely seriously. Technical measures are in place to prevent unauthorised or unlawful access to data and against accidental loss or destruction of, or damage to, data.\n[...]\nPaddle takes reasonable steps to help protect your personal information in an effort to prevent loss, misuse, and unauthorised access, disclosure, alteration and destruction. It is your responsibility to protect your user names and passwords to help prevent anyone from accessing or abusing your accounts and services. You should not use or reuse the same passwords you use with other accounts as your password for our services."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "We use the information we collect primarily to provide, maintain, protect and improve our current products and to develop new ones. We use personal information collected through our Site as described in this Policy or on our Site. For example, we may use your information to:\n[...]\nLink or combine it with other information we get from third parties, to help understand your needs and provide you with better service;"
]

[rubric.history]
value = "last-modified"
citations = [ "Last updated 11 April 2018" ]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "Paddle retains your data while you are a customer and will delete your information within 30 days of either party’s termination of the Terms upon written request."
]
notes = [
  "Inferring upon \"written request\" as an email or letter to the respective user."
]

[rubric.data-breaches]
value = "no"
notes = [
  "There is no proof showing that they would notify users in the case of a data breach."
]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "We do not share your personal information with third parties without your consent other than: With third parties who work on our behalf provided such third parties adhere to the data protection principles set out in the European Union Directive and/or Regulation on Data Protection or other applicable legilsation, or enter into a written agreement with Paddle requiring that the third party provide at least the same level of privacy protection as is required by such Principles; To comply with laws or to respond to lawful requests and legal process (provided that Paddle will endeavour to notify you if Paddle has received a lawful request for your information); To protect the rights and property of Paddle, our agents, customers and others including to enforce our agreements, policies and terms of use; In an emergency, including to protect the personal safety of any person; and For the purposes of a business deal (or negotiation of a business deal) involving sale or transfer of all or a part of our business or assets (business deals may include, for example, any merger, financing, acquisition, divestiture or bankruptcy transaction or proceeding)."
]
notes = [
  "According to NoScript, some notable connections are to Cloudfront, \"js.hsforms.net\" (CRM), and \"identity.netlify.com\" (CDN), as well as the notable Google Tag Manager."
]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "We use the information we collect primarily to provide, maintain, protect and improve our current products and to develop new ones. We use personal information collected through our Site as described in this Policy or on our Site. For example, we may use your information to: Improve our services, Site and how we operate our business; Understand and enhance your experience using our Site, products and services; Provide and deliver products and services you request; Process, manage, complete, and account for transactions; Provide customer support and respond to your requests, comments and inquiries; Invite you to participate in customer research; Create and manage online accounts you establish; Send you related information, including confirmations, invoices, technical notices, updates, security alerts and support and administrative messages; Communicate with you about promotions, upcoming events and news about products and services offered by Paddle and our selected partners; Link or combine it with other information we get from third parties, to help understand your needs and provide you with better service; and Comply with and enforce applicable legal requirements, industry standards, our policies, and our terms of use; and Protect, investigate and deter against fraudulent, unauthorised or illegal activity."
]

[rubric.noncritical-purposes]
value = "opt-out-all"
citations = [
  "You may opt out of receiving promotional emails from Paddle by following the instructions in those emails. If you opt out, we may still send you non-promotional emails, such as emails about your Paddle projects or our ongoing business relationship. You may also send requests about your contact preferences, changes and deletions to your information including requests to opt-out of sharing your personal information with third parties by emailing help@paddle.com. Paddle will respond within thirty (30) days to any request to delete your information. Individuals who have provided information to Paddle’s customers must send requests to change or delete such information to the particular Paddle customer."
]

[rubric.law-enforcement]
value = "strict"
citations = [
  "To comply with laws or to respond to lawful requests and legal process (provided that Paddle will endeavour to notify you if Paddle has received a lawful request for your information);"
]

[rubric.list-collected]
value = "generally"
citations = [
  "We collect information primarily to provide better services to all of our customers. We collect information you provide to us on our Site such as your name, email address, postal address, phone number, company name, payment information and demographics. We may also obtain information from other sources and combine that with information we collect on our Site.\n\nWhen you visit our Site, some information is automatically collected. This may include information such as the Operating System (OS) running on your device, Internet Protocol (IP) address, access times, browser type, and language, and the website you visited before our Site. We also collect information about how you use Paddle’s product(s).\n\nWe automatically collect information using “cookies” and Web beacons. Cookies are small data files stored on your hard drive by a website and web beacons are electronic images that may be used on our Site or in our emails. Among other things, cookies help us improve our Site, our marketing activities, and your experience. We use cookies to see which areas and features are popular and to count visits to our Site.\n\nMost Web browsers are set to accept cookies by default. If you prefer, you can choose to set your browser to remove cookies and to reject cookies. If you set your browser to reject cookies, some features will be unavailable. For more information on how to reject cookies, see your browser’s instructions on changing your cookie settings."
]

[rubric.revision-notify]
value = "no"
citations = [
  "Paddle may change this Policy from time to time. If we make any changes to this Policy, we will change the “Last Updated” date above. You agree that your continued use of our Services after such changes have been published to our Services will constitute your acceptance of such revised Policy."
]
