name = "Quantcast"
description = "Quantcast is an American company that specializes in AI-driven time advertising, audience insights, and measurement."
slug = "quantcast"
hostnames = [ "quantcast.com", "quantserve.com" ]
sources = [ "https://www.quantcast.com/privacy/", "https://www.quantcast.com/legal/quantcast-partners/" ]
contributors = [ "ibarakaiev" ]

[rubric.behavioral-marketing]
value = "yes"
citations = [
  "We have two main product suites: (1) [Quantcast Measure](https://www.quantcast.com/products/measure-audience-insights/) and (2) [Quantcast Advertise](https://www.quantcast.com/products/advertise/). Our Measure products help website owners to understand the interests and demographics of the people who visit their sites. (Here's an [example](https://www.quantcast.com/wp-content/uploads/2020/10/measure-us.pdf).) Our Advertise products allow businesses to deliver relevant online advertising to individual consumers. For companies that want to advertise online, our Advertise products help get their ads in front of the people that are more likely to find them interesting. For consumers, we provide ads that are more useful and relevant to their interests. And for websites, our Advertise products help drive advertising revenue, without which the free Internet we all use every day would not exist. In short, we try to make online advertising more efficient and pleasant for everyone. In order to do all this, we collect and analyze information about individual consumer interests and demographics."
]

[rubric.security]
value = "somewhat"
citations = [
  "We employ administrative, physical, and technical measures designed to protect the confidentiality and integrity of Personal Information that we store. These measures may include encryption and employment of information storage security technologies to restrict access to our network. Please be aware that no method of transmitting information over the Internet or storing information is completely secure. We have procedures and security features in place to help keep your data secure once we receive it. Additionally, in some instances our Partners or others may provide information to us in unencrypted form."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "These companies either directly license first and third party digital audience segment data from different sources (such as online, offline and mobile) to businesses or provide a platform through which Quantcast clients can collect, organize and activate such data for Quantcast’s use in connection with its advertising or analytics services. We share online identifiers (e.g., cookie IDs) with them in order to sync identifiers to effectively integrate with their services."
]

[rubric.history]
value = "last-modified"
citations = [
  "Effective: December 9, 2020."
]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "If you are a registered user, you may review, update, correct, or delete the information in your registration profile by logging into your account. If you want to delete your account, please contact us.\n\nIf you are located in the European Economic Area (EEA) and we can properly identify you, you have a number of rights with regard to your Personal Information. For example, you have the right to access your information and to have inaccuracies in your Personal Information corrected. In many cases where we process your information, you may also have a right to restrict or limit the ways in which we use your information. You also have the right to object to the processing of your Personal Information and to have it deleted in certain circumstances. You also have a right to obtain a copy of your Personal Information in an easily accessible format. For these purposes, go [here](https://www.quantcast.com/privacy/data-subject-rights/).\n\nHowever, as outlined above, although we make predictions about consumers' interests based on the information collected in accordance with this Privacy Policy, we don't collect, determine your identity, or know who you are. Accordingly, if we receive a request from you and we cannot identify you (even if you provide us with additional information), we may not be able to assist you in exercising these rights."
]

[rubric.data-breaches]
value = "na"
citations = [
  "Personal Information (also sometimes called “Personal Data”) is information that is associated with an individual and may enable that individual to be directly or indirectly identified. Through the use of our tags, SDKs, and cookies, we collect Personal Information about you; the Personal Information that Quantcast collects does not include information that may be used to identify you directly (for example, Quantcast does NOT collect your name or email address). However, Quantcast does collect information that may indirectly identify you. Some information transmitted by Cookies and Tags including Log Data are Personal Information. Quantcast may also receive some information about you from third parties and we may combine such information with personal information we collected about you ourselves. However, while we make predictions about your interests and demographics based on this information, we do not know who you are."
]
notes = [
  "Considering the kinds of personal data they collect, notification would be impossible."
]

[rubric.third-party-access]
value = "yes-specified-noncritical"
citations = [
  """
###### Information Shared with Our Partners

We share with third parties certain information, including Log Data, as part of providing and improving our products. For example, we disclose some of this data to companies involved in ad delivery or ad viewability. Likewise, we disclose some of this data in order to provide or facilitate site audience measurement, traffic analysis, or demographic analysis, and to enable websites to provide their advertisers with audience segments that are appropriate for their products or services. Since, as described in this Privacy Policy, we do not intentionally collect directly identifiable information about consumers (like your name or email address), we don’t share this type of information with Partners. To learn more about information that we share with our partners, please visit our [Partners page](https://www.quantcast.com/legal/quantcast-partners/).

###### Information Shared with Our Service Providers

We use third parties and Quantcast partners to help us administer and improve our products. For example, these companies assist with hosting, data processing, database management, and administrative tasks on our behalf. These third parties and partners have access to information about you, including through the placement of Tags on our Site, to perform these tasks on our behalf. To learn more about service providers for consumer information, please visit our [Partners page](https://www.quantcast.com/legal/quantcast-partners/).

###### Information Disclosed for Our Protection and the Protection of Others

It is our policy to protect you from having your privacy violated through abuse of the legal system. We reserve the right to disclose information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary: (i) to comply with any applicable laws, regulations, and valid subpoenas, warrants, and court orders; (ii) to protect the rights, property, and safety of ourselves, third parties, or the public in general; and (iii) to prevent or stop activity we consider to be illegal or unethical.

###### Information Disclosed in a Change of Ownership

Quantcast may sell, transfer, or otherwise share some or all of its assets, including information we collect about you, in connection with a merger, acquisition, reorganization, or sale of assets or in the event of bankruptcy. We may also make certain information available to a potential investor or purchaser (and their advisers) in advance of any such transaction completion.
  """
]

[rubric.data-collection-reasoning]
value = "mostly"
notes = [
  "The service explicitly explains the purposes for data collecting, however, not all data types are accompanied by a clear explanation."
]

[rubric.noncritical-purposes]
value = "opt-out-all"
notes = [
  """
If you prefer not to receive interest-based content and ads enabled by Quantcast, you can object and opt-out by clicking on the Quantcast “Opt Out” link [here](https://www.quantcast.com/opt-out). Additionally, we are a member of the Network Advertising Initiative (NAI) and participate in the Digital Advertising Alliance’s (DAA) Self-Regulatory Program. Each of these programs provides an opt-out feature where consumers can choose not to receive targeted advertising from any NAI or DAA affiliate. These links will take you to the [NAI opt out](http://www.networkadvertising.org/managing/opt_out.asp) and the [DAA opt out](http://www.aboutads.info/choices/). If you are located in the European Union, you may prefer to use the [EDAA opt out](http://www.youronlinechoices.eu/). If you choose to opt-out, we will place a cookie on your device which is associated with your browser that identifies you as having opted out. Then you will not receive interest-based content or advertisements enabled by Quantcast and we will not log your website visits or other online media consumption. Because our opt-out is cookie-based, your browser must be set to accept third party cookies. If you use multiple devices or browsers, you’ll have to opt out on each. If you delete the opt out cookie, you will need to opt-out again.

Where you have provided Quantcast with consent to use your data, you may revoke that consent at any time. Where you have used Quantcast Choice to provide your consent to Quantcast or other vendors, you may visit the website where you gave that consent at any time to update your choices.
  """
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "We may also retain information as is necessary to comply with our legal obligations, to resolve disputes, or to enforce our agreements."
]
notes = [
  "The policy does not explicitly mention how it handles legal requests, although it can be inferred from the citation that it will comply with any reasonable legal request."
]

[rubric.list-collected]
value = "generally"
citations = [
  """
When you visit a site or app operated by a Quantcast Partner, the Partner permits Quantcast to collect Log Data from their sites and apps through the use of Tags and Cookies; we also receive information directly from our Partners. We associate this information with a unique random identifier associated with your device (like a cookie ID), but we never associate it with your name, email, address, or phone number, because we don’t collect that type of directly identifying information about consumers. We use this information from Partners, which includes information about some of the sites you are visiting and some of the apps you are using, as necessary for our legitimate interests to help improve the accuracy of our products and to determine what advertisements and content might be interesting to you. For example, if you were recently searching for plane tickets to San Francisco, we might predict that you are interested in purchasing a nice warm sweater, and then show you an ad from one of our Advertising clients that sells sweaters. (To be more precise, we would predict that your device might belong to a person interested in sweaters, because we don’t know who you are.)

We do not link Log Data to your name, address, email, or phone number, or otherwise attempt to discover your identity. We employ appropriate organizational and technical security safeguards to keep information about you secure and to make it difficult for us to associate it with your identity.

When you visit a site or app that uses Quantcast Choice, we may use tags, cookies, SDKs, and plug-ins to store information about privacy notices that you have received and privacy choices that you have made. We do this pursuant to the IAB Europe Transparency & Consent Framework's policies and technical specifications. We do not use any information collected from Quantcast Choice for other purposes. In other words, we do not use that information to inform our Measure and Advertise products outside of understanding the privacy notices you have received and privacy choices you have made.
"""
]
notes = [
  "The service explains the personal data it collects generally well, however some \"such as\" phrases are used which make statements not absolute."
]

[rubric.revision-notify]
value = "yes"
citations = [
  "Any information that we collect is subject to the Privacy Policy in effect at the time that information is collected. We may revise this Privacy Policy from time to time, so please check this page regularly for updates. If we make any material changes to this Privacy Policy, we’ll notify you of those changes by posting them clearly on our website and/or by sending you an email or other notification, where feasible, and we'll indicate when such changes will become effective."
]
