name = "TikTok"
description = "TikTok is a social media app where users upload short videos, typically with music, owned by Chinese company ByteDance."
slug = "tiktok"
hostnames = [ "tiktok.com" ]
sources = [ "https://www.tiktok.com/legal/privacy-policy" ]
contributors = [ "bumbleben", "filex", "makai" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  "\"We may also use your information to, among other things, show you suggestions, promote the Platform, and customize your ad experience.\"",
  "\"We ask for your consent to access or use your information for specific purposes. If we do, you’ll always be able to revoke your consent through your device permissions or in-app settings.\""
]

[rubric.data-breaches]
value = "no"
notes = [
  "\"Not in policy.\""
]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "\"As explained below, we use your information to improve, support and administer the Platform, to allow you to use its functionalities, and to fulfill and enforce our Terms of Service. We may also use your information to, among other things, show you suggestions, promote the Platform, and customize your ad experience.\""
]

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "\"[...] delete your account by following the instructions [here](https://support.tiktok.com/en/account-and-privacy/deleting-an-account/deleting-an-account).\""
]

[rubric.history]
value = "last-modified"
citations = [
  "\"When we update the Privacy Policy, we will notify you by updating the “Last Updated” date at the top of the new Privacy Policy [...]\""
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "\"We may disclose any of the Information We Collect to respond to subpoenas, court orders, legal process, law enforcement requests, legal claims, or government inquiries, and to protect and defend the rights, interests, safety, and security of the Platform, our affiliates, users, or the public.\""
]

[rubric.list-collected]
value = "generally"
citations = [
  "\"Information You Provide [...] \nInformation From Other Sources [...] \nAutomatically Collected Information [...]\""
]

[rubric.noncritical-purposes]
value = "opt-out-some"
citations = [
  "\"- You may be able to control some of the Information We Collect through your device browser settings to refuse or disable Cookies. Because each browser is different, please consult the instructions provided by your browser. Please note that you may need to take additional steps to refuse or disable certain types of Cookies. In addition, your choice to disable Cookies is specific to the particular browser or device that you are using when you disable Cookies, so you may need to separately disable Cookies for each type of browser or device. If you choose to refuse, disable, or delete Cookies, some of the functionality of the Platform may no longer be available to you. Without this information, we are not able to provide you with all of the requested services. \n- You can navigate to \"Ads\" in your in-app settings to opt-out of targeted advertising based on personal information about your activity on nonaffiliated apps and websites. \n- You may be able to manage third-party advertising preferences for some of the third parties we work with to serve advertising across the Internet by using the choices available at https://www.networkadvertising.org/managing/opt_out.asp and https://www.aboutads.info/choices. \n- Your device may have controls that determine what Information We Collect. For example, you can control whether we can collect your mobile advertising identifier for advertising through settings on your Apple and Android devices. \n- You can opt out of marketing or advertising emails by using the “unsubscribe” link or mechanism noted in marketing or advertising emails. \n- Current versions of the app do not collect precise or approximate GPS information from U.S. users. If you are still using an older version that allowed for collection of precise or approximate GPS information (last release in August 2020) and you granted us permission to do so, you can prevent your device from sharing such information with the Platform at any time through your device’s operating system settings. \n- If you have registered for an account, you may access, review, and update certain personal information that you have provided to us by logging into your account and using available features and functionalities. \n- Some browsers transmit “do-not-track” signals to websites. Because of differences in how browsers incorporate and activate this feature, we currently do not take action in response to these signals.\""
]

[rubric.revision-notify]
value = "yes"
citations = [
  "\"When we update the Privacy Policy, we will notify you by updating the “Last Updated” date at the top of the new Privacy Policy, posting the new Privacy Policy, or providing any other notice required by applicable law.\""
]

[rubric.security]
value = "somewhat"
citations = [
  "\"We use reasonable measures to help protect information from loss, theft, misuse, unauthorized access, disclosure, alteration, or destruction.\""
]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "\"Service Providers and Business Partners [...]\nWithin Our Corporate Group [...] \nIn Connection with a Sale, Merger, or Other Business Transfer [...] \nFor Legal Reasons [...] \nWith Your Consent [...]\""
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "\"Information From Other Sources\n\nAdvertising, Measurement and Other Partners. Advertisers, measurement and other partners share information with us about you and the actions you have taken outside of the Platform, such as your activities on other websites and apps or in stores, including the products or services you purchased, online or in person. These partners also share information with us, such as mobile identifiers for advertising, hashed email addresses and phone numbers, and cookie identifiers, which we use to help match you and your actions outside of the Platform with your TikTok account. Some of our advertisers and other partners enable us to collect similar information directly from their website or app by integrating our TikTok Advertiser Tools (such as TikTok Pixel). These partners are required to have the necessary rights and permissions to share your information with us before doing so. We process certain information that we receive from these partners as a joint controller with them. Learn more about our arrangements with these partners.\nSellers, Payment and Transaction Fulfillment Providers. We receive information about you from sellers as well as payment and transaction fulfillment providers, such as payment confirmation details, and information about the delivery of products you have purchased through our shopping features.\nThird Party Platforms and Partners. Third party platforms provide us with information (such as your email address, authentication ID, and public profile) when you choose to sign up for or log in to the Platform using sign-in features provided by those third parties. We may also receive contact information that you hold or is held about you when contact information is synced with our Platform by you or another user. When you interact with any third party service (such as third party apps, websites or products) that integrate TikTok Developer Tools, we will receive the information necessary to provide you with features like cross-service authentication or cross-posting. For example, this will happen if you log in to another platform with your TikTok account or if you use TikTok’s “share” button on a third party platform to share content from there to the Platform. We may also receive information from third party providers which we use for safety purposes, including to protect users on the Platform and for content moderation.\nAdditional Sources. We may collect or receive information about you from organisations, businesses, people, and others, including, for example, publicly available sources, government authorities, professional organisations, and charity groups. We also collect information about you where you are included or mentioned in User Content, Messages, in a complaint, appeal, request or feedback submitted by a user or third party, or if your contact information is provided to us by a user.\""
]


