name = "X / (Formerly Known As Twitter)"
description = "Twitter is a microblogging social network popular among the masses."
date = 2023-11-20
slug = "twitter"
hostnames = [ "x.com", "twitter.com", "ads-twitter.com" ]
sources = [ "https://twitter.com/en/privacy" ]
contributors = [ "milesmcc", "SimplyUnknown" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  "\"Advertising revenue enables us to provide our products and services. Advertisers may learn information from your engagement with their ads on or off X. For example, if you click on an external link or ad on our services, that advertiser or website operator might figure out that you came from X, along with other information associated with the ad you clicked, such as characteristics of the audience it was intended to reach and other X-generated identifiers for that ad. They may also collect other personal information from you, such as cookie identifiers, or your IP address.\"\n\n\"X adheres to the Digital Advertising Alliance Self-Regulatory Principles for Online Behavioral Advertising (also referred to as “interest-based advertising”) and respects the DAA’s consumer choice tool for you to opt out of interest-based advertising at https://optout.aboutads.info/.\""
]

[rubric.security]
value = "no"
notes = [
  "The policy does not mention any security measures X takes to secure its data (though X does _not_ have a history of data breaches)."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "\"Our ad and business partners share information with us such as browser cookie IDs, X-generated identifiers, mobile device IDs, hashed user information like email addresses, demographic or interest data, and content viewed or actions taken on a website or app. Some of our ad partners, particularly our advertisers, also enable us to collect similar information directly from their website or app by integrating our advertising technology. Information shared by ad partners and affiliates or collected by X from the websites and apps of ad partners and affiliates may be combined with the other information you share with X and that X receives, generates, or infers about you described elsewhere in this Privacy Policy.\""
]

[rubric.history]
value = "yes"
notes = [
  "At the bottom of the policy, the last modified date as well as previous policy revisions are available."
]

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "\"If you follow the instructions here, your account will be deactivated and your data will be queued for deletion. When deactivated, your X account, including your display name, username, and public profile, will no longer be viewable on X.com, X for iOS, and X for Android. For up to 30 days after deactivation it is still possible to restore your X account if it was accidentally or wrongfully deactivated.\""
]

[rubric.data-breaches]
value = "no"
notes = [ "The policy does not specify a data breach protocol." ]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "\"We may share your information with our service providers that perform functions and provide services on our behalf, including payment services providers who facilitate payments; service providers that host our various blogs and wikis; service providers that help us understand the use of our services; applicant tracking system providers to send and receive applicant and job data to potential employers; and those that provide fraud detection services.\"\n\n\"We share or disclose your information with your consent or at your direction, such as when you authorize a third-party web client or application to access your account or when you direct us to share your feedback with a business. Similarly, to improve your experience, we work with third-party partners to display their video content on X or to allow cross-platform sharing. When you watch or otherwise interact with content from our video or cross-platform sharing partners, they may receive and process your personal information as described in their privacy policies. For video content, you can adjust your autoplay settings if you prefer that content not to play automatically.\""
]

[rubric.data-collection-reasoning]
value = "yes"
notes = [
  "The policy clearly explains why it collects essentially all data, including data used almost solely for marketing purposes. While the amount of data it collects is not ideal, X is very transparent about it."
]

[rubric.noncritical-purposes]
value = "opt-out-some"
notes = [
  "X has relatively comprehensive privacy settings, but Google Analytics monitors users on X regardless of their privacy settings."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "\"We may preserve, use, share, or disclose your information if we believe that it is reasonably necessary to: comply with a law, regulation, legal process, or governmental request; protect the safety of any person, protect the safety or integrity of our platform, including to help prevent spam, abuse, or malicious actors on our services; explain why we have removed content or accounts from our services (e.g., for a violation of Our Rules); address fraud, security, or technical issues; or protect our rights or property, or the rights or property of those who use our services.\""
]

[rubric.list-collected]
value = "exhaustively"
notes = [
  "X breaks down the information in which they request into 3 sections, and breaks down further each subsection outlineling near exactly the information in which they take."
]

[rubric.revision-notify]
value = "yes"
citations = [
  "\"If we do revise this Privacy Policy and make changes that are determined by us to be material, we will provide you notice and an opportunity to review the revised Privacy Policy before you continue to use X.\""
]
