name = "Twitter"
description = "Twitter is a microblogging social network popular among the masses."
slug = "twitter"
hostnames = [ "twitter.com", "ads-twitter.com" ]
sources = [ "https://twitter.com/en/privacy" ]
contributors = [ "milesmcc" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  "\"Advertising revenue allows us to support and improve our services. We use the information described in this Privacy Policy to help make our advertising more relevant to you, to measure its effectiveness, and to help recognize your devices to serve you ads on and off of Twitter.\"\n\n\"Twitter adheres to the Digital Advertising Alliance Self-Regulatory Principles for Online Behavioral Advertising (also referred to as “interest-based advertising”) and respects the DAA’s consumer choice tool for you to opt out of interest-based advertising at https://optout.aboutads.info. In addition, our ads policies prohibit advertisers from targeting ads based on categories that we consider sensitive or are prohibited by law, such as race, religion, politics, sex life, or health. Learn more about your privacy options for interest-based ads here and about how ads work on our services here.\""
]

[rubric.security]
value = "no"
notes = [
  "The policy does not mention any security measures Twitter takes to secure its data (though Twitter does _not_ have a history of data breaches)."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "\"We may receive information about you from third parties who are not our ad partners, such as others on Twitter, partners who help us evaluate the safety and quality of content on our platform, our corporate affiliates, and other services you link to your Twitter account.\"\n\n\"Our ad partners and affiliates share information with us such as browser cookie IDs, mobile device IDs, hashed email addresses, demographic or interest data, and content viewed or actions taken on a website or app.\""
]

[rubric.history]
value = "yes"
notes = [
  "At the bottom of the policy, the last modified date as well as previous policy revisions are available."
]

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "\"We keep Log Data for a maximum of 18 months. If you follow the instructions here (or for Periscope here), your account will be deactivated and then deleted. When deactivated, your Twitter account, including your display name, username, and public profile, will no longer be viewable on Twitter.com, Twitter for iOS, and Twitter for Android. For up to 30 days after deactivation it is still possible to restore your Twitter account if it was accidentally or wrongfully deactivated.\"\n\n\"Twitter provides you a means to download the information you have shared through our services by following the steps here. Periscope provides you a means to download the information you have shared through our services by following the steps here.\""
]

[rubric.data-breaches]
value = "no"
notes = [ "The policy does not specify a data breach protocol." ]

[rubric.third-party-access]
value = "yes-unspecified-critical"
citations = [
  "\"We engage service providers to perform functions and provide services to us in the United States, Ireland, and other countries. For example, we use a variety of third-party services to help operate our services, such as hosting our various blogs and wikis, and to help us understand the use of our services, such as Google Analytics.\""
]

[rubric.data-collection-reasoning]
value = "yes"
notes = [
  "The policy clearly explains why it collects essentially all data, including data used almost solely for marketing purposes. While the amount of data it collects is not ideal, Twitter is very transparent about it."
]

[rubric.noncritical-purposes]
value = "opt-out-some"
notes = [
  "Twitter has relatively comprehensive privacy settings, but Google Analytics monitors users on Twitter regardless of their privacy settings."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "\"Notwithstanding anything to the contrary in this Privacy Policy or controls we may otherwise offer to you, we may preserve, use, or disclose your personal data if we believe that it is reasonably necessary to comply with a law, regulation, legal process, or governmental request...\""
]

[rubric.list-collected]
value = "generally"
notes = [
  "While the policy is generally explicit about the data Twitter collects, it nonetheless uses qualifying phrases like \"such as\" when listing collected data."
]

[rubric.revision-notify]
value = "yes"
citations = [
  "\"We may revise this Privacy Policy from time to time. The most current version of the policy will govern our processing of your personal data and will always be at https://twitter.com/privacy. If we make a change to this policy that, in our sole discretion, is material, we will notify you via an @Twitter update or email to the email address associated with your account. By continuing to access or use the Services after those changes become effective, you agree to be bound by the revised Privacy Policy.\""
]
