# Generated by Django 2.2.3 on 2019-07-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.TextField(blank=True, default=''),
        ),
    ]
