# Generated by Django 2.2.3 on 2019-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190729_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
