# Generated by Django 2.2.3 on 2019-07-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rubricselection_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
