# Generated by Django 2.2.3 on 2019-07-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190729_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
