# Generated by Django 2.2.3 on 2019-07-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_privacypolicy_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubricoption',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='rubricquestion',
            old_name='name',
            new_name='text',
        ),
        migrations.AddField(
            model_name='rubricquestion',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rubricselection',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
