# Generated by Django 2.2.3 on 2019-07-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190729_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubricselection',
            old_name='description',
            new_name='note',
        ),
    ]
