# Generated by Django 2.2.3 on 2019-07-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190729_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('token', models.TextField()),
                ('expires', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
