# Generated by Django 2.2.3 on 2019-07-31 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_privacypolicy_cached_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField()),
                ('text', models.TextField()),
                ('status', models.CharField(default='O', max_length=1)),
                ('comment', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PrivacyPolicy')),
                ('rubric_selection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.RubricSelection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='suggestedaction',
            name='edit',
        ),
        migrations.DeleteModel(
            name='Edit',
        ),
        migrations.DeleteModel(
            name='SuggestedAction',
        ),
    ]
