# Generated by Django 2.2.3 on 2019-07-31 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190731_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
