# Generated by Django 2.2.3 on 2019-07-31 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190731_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hostname',
            field=models.TextField(default='UNSET'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='rubric_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.RubricSelection'),
        ),
    ]
