# Generated by Django 2.2.3 on 2019-07-31 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190731_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='history',
        ),
    ]
