# Generated by Django 2.2.3 on 2019-07-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_suggestion_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
