# Generated by Django 2.2.3 on 2019-08-01 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190731_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PrivacyPolicy'),
        ),
    ]
