# Generated by Django 2.2.4 on 2019-08-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190802_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='hostname',
            field=models.TextField(db_index=True, default='UNSET'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(db_index=True),
        ),
    ]
