# Generated by Django 2.2.4 on 2019-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190806_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following_products',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
