# Generated by Django 2.2.4 on 2019-08-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190827_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricquestion',
            name='category',
            field=models.TextField(default='Unknown'),
        ),
    ]
