# Generated by Django 2.2.4 on 2019-08-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rubricquestion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='cached_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.TextField(blank=True, default='', help_text='Use https://www.base64-image.de/'),
        ),
    ]
