# Generated by Django 2.2.4 on 2019-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190827_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginkey',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
