# Generated by Django 2.2.4 on 2019-08-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_loginkey_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginkey',
            name='redirect',
            field=models.TextField(blank=True, default=''),
        ),
    ]
