# Generated by Django 2.2.4 on 2019-08-30 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_loginkey_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maintainers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
