# Generated by Django 2.2.4 on 2019-09-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_product_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_email_blast',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
