# Generated by Django 2.2.5 on 2019-09-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_last_email_blast'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='highlighted_snapshot',
            field=models.TextField(blank=True),
        ),
    ]
